### ISSUE TITLE
I think this library will be great if ...

### ISSUE THREAD

**Issue by octarudin** [AlexandreHiroyuki/MovingAveragePlus#41]
Hi, Thanks for creating an awesome library.
I just want to give you a suggest, I think this library will be great if added with other statistical function such as standard deviation of samples, variance, etc. That's all. Best regards, Octa.

**Comment by AlexandreHiroyuki** [comment]
Hey, thanks for the feedback!

I'm solving some private problems now, but I will consider that as soon as I find time.

**Comment by AlexandreHiroyuki** [comment]
I plan to implement automated tests to make new features more consistent.
The next thing to do is to implement your idea!

**Comment by AlexandreHiroyuki** [comment]
I had to make too many breaking changes to allow better addition of new features.
So, I decided to open a [new repository for the following releases](https://github.com/AlexandreHiroyuki/DataTome/issues/4).

Please consider giving your support to the continuation of this project!
